name: yemenshabab
description: "YemenShabab News Mobile"

publish_to: 'none'

version: 1.4.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  http: ^1.2.1
  flutter_advanced_drawer: ^1.3.6
  animated_bottom_navigation_bar: ^1.3.3
  flutter_zoom_drawer: ^3.2.0
  intl: ^0.19.0
  toastification: ^2.0.0
  shared_preferences: ^2.2.3
  buildcondition: ^0.0.4
  dynamic_tabbar: ^1.0.7
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  circular_reveal_animation: ^2.0.1
  flutter_staggered_animations: ^1.1.1
  font_awesome_flutter: ^10.7.0
  fluttertoast: ^8.2.6
  icon_broken: ^1.1.0
  rounded_loading_button_plus: ^3.0.1
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  auto_mappr: ^2.5.0
  flutter_widget_from_html_core: ^0.15.1
  animated_toggle_switch: ^0.8.2
  chewie: ^1.8.1
  video_player: ^2.9.1
  qyplayer: ^0.1.2
  lecle_yoyo_player: ^0.0.8
  infinite_scroll_pagination: ^4.0.0
  animation_search_bar: ^0.0.10
  #  youtube_player_flutter: ^9.0.1
  youtube_player_iframe: ^5.1.3
  share_plus: ^9.0.0
  loading_animations: ^2.2.0
  loading_animation_widget: ^1.2.1
  loader_skeleton: ^0.0.4
  webview_flutter: ^4.8.0
  timezone: ^0.9.4
  flutter_timezone: ^2.0.1
  url_launcher: ^6.3.0
  pip_view: ^0.9.7
  cached_network_image: ^3.3.1
  audio_video_progress_bar: ^2.0.3
  just_audio: ^0.9.38
  just_audio_background: ^0.0.1-beta.12
  rxdart: ^0.27.7
  just_audio_platform_interface: ^4.3.0
  settings_ui: ^2.0.2
  floating: ^4.0.0
  widget_zoom: ^0.0.4
  ribbon_widget: ^1.0.5
  syncfusion_flutter_sliders: ^26.1.42
  get: ^4.6.6
  google_fonts: ^6.2.1
  auto_size_text: ^3.0.0
  hovering: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.6.0
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/noto/NotoSansArabic-Black.ttf
          weight: 900
        - asset: assets/fonts/noto/NotoSansArabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/noto/NotoSansArabic-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/noto/NotoSansArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/noto/NotoSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/noto/NotoSansArabic-Light.ttf
          weight: 300
        - asset: assets/fonts/noto/NotoSansArabic-Thin.ttf
          weight: 100
        - asset: assets/fonts/noto/NotoSansArabic-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/noto/NotoSansArabic-SemiBold.ttf
          weight: 600
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf