const programJson = {
  "programs": [
    {
      "uuid": "da457ce2-6162-4153-81ac-505a9a9a4329",
      "image":
          "https://yemenshabab.net/upimages/programs/YemenShabab2022-03-24-06-25-47-101423.jpg",
      "title": "Late Night Show",
      "description": "Entertainment and interviews with celebrities.",
      "time": "11:00 PM",
      "titleAr": "برنامج المساء",
      "descriptionAr": "ترفيه ومقابلات مع المشاهير.",
      "timeAr": "",
      "playlistId": "13",
      "schedule": "DAILY",
      "views": "170",
      "creationDate": "",
      "createdBy": "",
      "days": "WEEKLY",
      "lastModificationDate": "",
      "modifiedBy": ""
    },
    {
      "uuid": "24fb2f2d-2f8c-4208-bb69-3d6a97f19d09",
      "image":
          "https://yemenshabab.net/upimages/programs/YemenShabab2022-10-01-05-47-35-520748.jpg",
      "title": "Art and Culture",
      "description": "Exploring various forms of art and cultural expressions.",
      "time": "07:00 PM",
      "titleAr": "الفن والثقافة",
      "descriptionAr": "استكشاف أشكال مختلفة من الفن والتعبيرات الثقافية.",
      "timeAr": "",
      "playlistId": "12",
      "schedule": "DAILY",
      "views": "100",
      "creationDate": "",
      "createdBy": "",
      "days": "WEEKLY",
      "lastModificationDate": "",
      "modifiedBy": ""
    },
    {
      "uuid": "6abd7b38-a3dc-4adb-b380-70a810b693ec",
      "image":
          "https://yemenshabab.net/upimages/programs/YemenShabab2022-10-04-03-19-44-124814.jpg",
      "title": "Evening Talk Show",
      "description": "Discussions on current events and interesting topics.",
      "time": "08:00 PM",
      "titleAr": "برنامج حواري مسائي",
      "descriptionAr": "مناقشات حول الأحداث الجارية ومواضيع مثيرة للاهتمام.",
      "timeAr": "",
      "playlistId": "11",
      "schedule": "DAILY",
      "views": "180",
      "creationDate": "",
      "createdBy": "",
      "days": "WEEKLY",
      "lastModificationDate": "",
      "modifiedBy": ""
    },
    {
      "uuid": "474b7bc5-c473-46ef-8adc-b3517a9b25ab",
      "image":
          "https://yemenshabab.net/upimages/programs/YemenShabab2019-05-11-02-57-14-326488.png",
      "title": "Kids Corner",
      "description": "Fun and educational content for children.",
      "time": "09:00 AM",
      "titleAr": "ركن الأطفال",
      "descriptionAr": "محتوى ممتع وتعليمي للأطفال.",
      "timeAr": "",
      "playlistId": "10",
      "schedule": "DAILY",
      "views": "140",
      "creationDate": "",
      "createdBy": "",
      "days": "WEEKLY",
      "lastModificationDate": "",
      "modifiedBy": ""
    },
    {
      "uuid": "66473a68-432e-4f5f-b4d5-dbad3b1f7299",
      "image":
          "https://yemenshabab.net/upimages/programs/YemenShabab2022-10-01-06-31-06-977579.jpg",
      "title": "Business Insights",
      "description": "The latest news and trends in the business world.",
      "time": "01:00 PM",
      "titleAr": "تحليلات الأعمال",
      "descriptionAr": "أحدث الأخبار والاتجاهات في عالم الأعمال.",
      "timeAr": "",
      "playlistId": "9",
      "schedule": "DAILY",
      "views": "160",
      "creationDate": "",
      "createdBy": "",
      "days": "WEEKLY",
      "lastModificationDate": "",
      "modifiedBy": ""
    },
    {
      "uuid": "63f015c4-bafa-4aae-a21c-e4eec661056c",
      "image":
          "https://yemenshabab.net/upimages/programs/YemenShabab2023-09-25-42223.png",
      "title": "Travel Diaries",
      "description": "Exploring beautiful destinations around the world.",
      "time": "03:00 PM",
      "titleAr": "مذكرات السفر",
      "descriptionAr": "استكشاف وجهات جميلة حول العالم.",
      "timeAr": "",
      "playlistId": "8",
      "schedule": "DAILY",
      "views": "130",
      "creationDate": "",
      "createdBy": "",
      "days": "DAILY",
      "lastModificationDate": "",
      "modifiedBy": ""
    },
    {
      "uuid": "572d04e8-182f-4472-a861-47d0301902cd",
      "image":
          "https://yemenshabab.net/upimages/programs/YemenShabab2024-03-09-03-02-33-387727.jpg",
      "title": "Health & Wellness",
      "description": "Tips and advice for a healthy lifestyle.",
      "time": "10:00 AM",
      "titleAr": "الصحة والعافية",
      "descriptionAr": "نصائح وإرشادات لحياة صحية.",
      "timeAr": "",
      "playlistId": "7",
      "schedule": "DAILY",
      "views": "85",
      "creationDate": "",
      "createdBy": "",
      "days": "DAILY",
      "lastModificationDate": "",
      "modifiedBy": ""
    },
    {
      "uuid": "1fd10c60-5059-45b3-bf8f-d2f2252db6a1",
      "image":
          "https://yemenshabab.net/upimages/programs/YemenShabab2024-03-09-02-54-34-864196.jpg",
      "title": "Tech Today",
      "description": "Exploring the latest in technology and innovation.",
      "time": "04:00 PM",
      "titleAr": "تكنولوجيا اليوم",
      "descriptionAr": "استكشاف أحدث ما في التكنولوجيا والابتكار.",
      "timeAr": "",
      "playlistId": "6",
      "schedule": "DAILY",
      "views": "110",
      "creationDate": "",
      "createdBy": "",
      "days": "DAILY",
      "lastModificationDate": "",
      "modifiedBy": ""
    },
    {
      "uuid": "572d04e8-182f-4472-a861-47d030190cca",
      "image":
          "https://yemenshabab.net/upimages/programs/YemenShabab2024-03-09-02-48-46-661727.jpg",
      "title": "Cooking Show",
      "description": "Delicious recipes and cooking tips from top chefs.",
      "time": "11:00 AM",
      "titleAr": "برنامج الطبخ",
      "descriptionAr": "وصفات لذيذة ونصائح طهي من كبار الطهاة.",
      "timeAr": "",
      "playlistId": "5",
      "schedule": "DAILY",
      "views": "90",
      "creationDate": "",
      "createdBy": "",
      "days": "DAILY",
      "lastModificationDate": "",
      "modifiedBy": ""
    },
    {
      "uuid": "572d04e8-182f-4472-a861-47d030190ccf",
      "image":
          "https://yemenshabab.net/upimages/programs/YemenShabab2024-03-09-02-56-40-447073.png",
      "title": "Sports Roundup",
      "description": "Latest updates and analysis on the world of sports.",
      "time": "09:00 PM",
      "titleAr": "جولة رياضية",
      "descriptionAr": "أحدث التحديثات والتحليلات في عالم الرياضة.",
      "timeAr": "",
      "playlistId": "4",
      "schedule": "DAILY",
      "views": "150",
      "creationDate": "",
      "createdBy": "",
      "days": "DAILY",
      "lastModificationDate": "",
      "modifiedBy": ""
    },
    {
      "uuid": "572d04e8-182f-4472-a861-47d030190ccd",
      "image":
          "https://yemenshabab.net/upimages/programs/YemenShabab2024-03-09-03-05-57-221654.jpg",
      "title": "Documentary Hour",
      "description": "In-depth documentaries on various topics.",
      "time": "02:00 PM",
      "titleAr": "ساعة وثائقية",
      "descriptionAr": "وثائقيات متعمقة عن مواضيع مختلفة.",
      "timeAr": "",
      "playlistId": "3",
      "schedule": "DAILY",
      "views": "75",
      "creationDate": "",
      "createdBy": "",
      "days": "WEEKLY",
      "lastModificationDate": "",
      "modifiedBy": ""
    },
    {
      "uuid": "d4357b25-994b-41a9-90e0-08393c0b98c4",
      "image":
          "https://yemenshabab.net/upimages/programs/YemenShabab2024-03-09-06-49-00-913735.jpg",
      "title": "Evening News",
      "description":
          "Comprehensive coverage of the days events and breaking news.",
      "time": "06:00 PM",
      "titleAr": "أخبار المساء",
      "descriptionAr": "تغطية شاملة لأحداث اليوم والأخبار العاجلة.",
      "timeAr": "",
      "playlistId": "2",
      "schedule": "DAILY",
      "views": "200",
      "creationDate": "",
      "createdBy": "",
      "days": "DAILY",
      "lastModificationDate": "",
      "modifiedBy": ""
    },
    {
      "uuid": "ee4b8eab-ee35-44ba-a500-adc78bab04ac",
      "image":
          "https://yemenshabab.net/upimages/programs/YemenShabab2024-03-10-09-22-29-724162.jpg",
      "title": "Morning Show",
      "description":
          "A lively start to your day with news, interviews, and entertainment.",
      "time": "08:00 AM",
      "titleAr": "برنامج الصباح",
      "descriptionAr":
          "بداية مفعمة بالحيوية ليومك مع الأخبار والمقابلات والترفيه.",
      "timeAr": "",
      "playlistId": "1",
      "schedule": "DAILY",
      "views": "120",
      "creationDate": "",
      "createdBy": "",
      "days": "DAILY",
      "lastModificationDate": "",
      "modifiedBy": ""
    }
  ],
  "totalRecords": "13"
};
