// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPLxQhC5L1iMxuhRzAGSNNYnF950_XA1M',
    appId: '1:653978673733:web:28395bb507a2cb94c9792c',
    messagingSenderId: '653978673733',
    projectId: 'yemenshabab-853a4',
    authDomain: 'yemenshabab-853a4.firebaseapp.com',
    storageBucket: 'yemenshabab-853a4.appspot.com',
    measurementId: 'G-4W6M317Q83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDvVodKES5gKpngSdOJFyeW4Gq5-uOvF4',
    appId: '1:653978673733:android:d77d41abffd2f25bc9792c',
    messagingSenderId: '653978673733',
    projectId: 'yemenshabab-853a4',
    storageBucket: 'yemenshabab-853a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxUY9PBJFjnwzAxhNxT2nJQFVkXEm8Q-Q',
    appId: '1:653978673733:ios:54f068276fe7b745c9792c',
    messagingSenderId: '653978673733',
    projectId: 'yemenshabab-853a4',
    storageBucket: 'yemenshabab-853a4.appspot.com',
    iosBundleId: 'net.yemenshabab',
  );

}